# Theme settings
doks:
    baseurl: https://dqs.dewy.dev/
    color_theme: blue
    header:
        logo:
            text: DQS
        nav:
            - item_name: Home
              item_url: 'https://dqs.dewy.dev/'
            - item_name: About
              item_url: 'https://dqs.dewy.dev/about'
            - item_name: Buy
              item_url: 'https://dqs.dewy.dev/buy'
            - item_name: FAQ
              item_url: 'https://dqs.dewy.dev/faq'
            - item_name: Support
              item_url: 'https://dqs.dewy.dev/support'
    footer:
        content:
            logo:
                text: DQS
                image:
            copyright: Copyright &copy; 2020 - Dewy Software <br>All rights reserved. <br><br>DQS v3.0.0; made with <3 by Dewy.
        social_list:
            - network_name: gitlab
              profile_url: 'https://gitlab.com/dewysoftware/'
            - network_name: github
              profile_url: 'https://github.com/dewysoftware/'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/channel/UCKWk27Y5JH-heB7-e9Tojlw'
    google_analytics:
        tracking_code: UA-171053082-1
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./core/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./core/_layouts
includes_dir: ./core/_includes
exclude: [ 'README.md', 'default.md' ]
permalink: /:title/
