# Theme settings
doks:
    baseurl: https://dewy.dev/dqs
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: DQS
        nav:
            - item_name: Jimblo
              item_url: 'https://dewy.dev/dqs/buy'
    footer:
        content:
            logo:
                text: DQS
                image:
            copyright: Copyright &copy; 2020 - Dewy Software <br>All rights reserved.
        social_list:
            - network_name: gitlab
              profile_url: 'https://gitlab.com/dewysoftware/'
            - network_name: github
              profile_url: 'https://github.com/dewysoftware/'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./core/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./core/_layouts
includes_dir: ./core/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
